// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "7463fe72-8cdc-4da2-b98a-eae1ee465c3d";

const char SSID[]               = "ZTE_2.4G_EAA2";    // Network SSID (name)
const char PASS[]               = "13141516";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "e1ESyR8fS#ryMxY0LmcER6QbK";    // Secret device password

void onBackDistanceChange();
void onXPwmChange();
void onYPwmChange();
void onGoBackChange();
void onLightCarChange();

float back_distance;
float x_pwm;
float y_pwm;
bool go_back;
bool light_car;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(back_distance, READWRITE, ON_CHANGE, onBackDistanceChange);
  ArduinoCloud.addProperty(x_pwm, READWRITE, ON_CHANGE, onXPwmChange);
  ArduinoCloud.addProperty(y_pwm, READWRITE, ON_CHANGE, onYPwmChange);
  ArduinoCloud.addProperty(go_back, READWRITE, ON_CHANGE, onGoBackChange);
  ArduinoCloud.addProperty(light_car, READWRITE, ON_CHANGE, onLightCarChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
