// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "60e1a612-aea6-48ad-8576-728b4bd60a0f";

const char SSID[]               = "ZTE_2.4G_EAA2";    // Network SSID (name)
const char PASS[]               = "13141516";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "0uwqEIgjBDDXdhdnsRx?Bp16c";    // Secret device password

void onLed2Change();

bool led2;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(led2, READWRITE, ON_CHANGE, onLed2Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
