// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "f6bcf454-70e6-497e-ad5a-7cf9c34912ab";

const char SSID[]               = "ZTE_2.4G_EAA2";    // Network SSID (name)
const char PASS[]               = "13141516";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "MapxSBqttrKJ?cQ2vfnwpEY!R";    // Secret device password

void onXCloudChange();
void onYCloudChange();
void onMiddleButtonChange();

float x_cloud;
float y_cloud;
int middle_button;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(x_cloud, READWRITE, ON_CHANGE, onXCloudChange);
  ArduinoCloud.addProperty(y_cloud, READWRITE, ON_CHANGE, onYCloudChange);
  ArduinoCloud.addProperty(middle_button, READWRITE, ON_CHANGE, onMiddleButtonChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);